stages:
  - build
  - deploy

opensuse:
  image: drfaustroll/esl:tumbleweed
  stage: build
  script:
    - sh utils/opensuse-gcc-openmpi.sh

  
opensuse-paranoid:
  image: drfaustroll/esl:tumbleweed
  stage: build
  script:
    - sh utils/opensuse-paranoid.sh

debian:
  image: drfaustroll/esl:debian
  stage: build
  script:
    - sh utils/debian-gcc-openmpi.sh

debian-paranoid:
  image: drfaustroll/esl:debian
  stage: build
  script:
    - sh utils/debian-paranoid.sh
pages:
  image: drfaustroll/esl:tumbleweed
  stage: deploy
  script:
    - sh utils/opensuse-docs.sh
    - ls && pwd
    - cp -r doc/developers/source/* public/developers/
    - cp -r doc/manual/_build/html/* public/
  artifacts:
      paths:
        - public/* 

